# Step 1 - Building the React Application
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Step 2 - Create a new lightweight image to serve the built files
FROM node:20-alpine

WORKDIR /app

COPY ./webserver ./

COPY --from=build /app/dist ./dist

RUN npm install

# Install PM2 globally
RUN npm install -g pm2

EXPOSE 5173

# Start the app with PM2
CMD ["pm2-runtime", "start", "ecosystem.config.js"]